README.md, dist/index.js, src/main.ts
Paths can be negated to stop searching through the remaining patterns in
a the glob list. All changed files tested and at least one matching file
will result in a label being added.
Fixes actions/labeler#9
=> Add support for exclusions

dist/index.js, src/main.ts
The previous logic had a bug where the "any" pattern list could match
against changed files even when not all globs matched a single changed
file. The bug arose individual globs in the "any" list were tested
against all changed files individually. Therefore, as long as at least
one changed file matched an individual glob in the list, a successful
match would be found.
The correct behavior is to match all the globs in the list against each
individual file. This ensures that is possible to define exlcusions
correctly and matched the documented behavior.
=> Fix "any" matching when not all globs match

__tests__/main.test.ts, action.yml, dist/index.js, src/main.ts
Big thank you to @kevinphelps for https://github.com/actions/labeler/pull/63 (closes #14) and @Co-qn for https://github.com/actions/labeler/pull/43 (closes #42)
I just took those changes verbatim and rebased them and re-created this for simplicity. In the future I will *ideally continue to merge existing PRs rather than create new ones* but given their age I felt it reasonable to recreate them here so they'd be rebased, I could generate an up to date build, and run the formatting
=> Paginate and remove old labels

README.md
GitHub [has introduced](https://github.blog/2020-08-03-github-actions-improvements-for-fork-and-pull-request-workflows/) a new event type: `pull_request_target`, which allows to run workflows from base branch and pass a token with write permission.
> In order to solve this, we’ve added a new `pull_request_target` event, which behaves in an almost identical way to the `pull_request` event with the same set of filters and payload. However, instead of running against the workflow and code from the merge commit, the event runs against the workflow and code from the base of the pull request. This means the workflow is running from a trusted source and is given access to a read/write token as well as secrets enabling the maintainer to safely comment on or label a pull request. This event can be …
=> Update README to use `pull_request_target` event

README.md
Awhile back we switched from `master` to `main`. Looks like one minor commit got added to `master` but not `main`.
After this I can just delete `master` so there's less confusion in the future.
=> 🧹 Merge commits from "master" into "main"

CODE_OF_CONDUCT.md, CONTRIBUTING.md, README.md, action.yml, docs/development.md
- Document the release process in `CONTRIBUTING.md`
- Add development instructions to `CONTRIBUTING.md` (adapted from [download-artifact](https://github.com/actions/download-artifact))
- Add a test badge to the `README`
- Link to `CONTRIBUTING.md` in `README`
- Unify copy between `README.md` and `action.yml`
- Copy-pasta the CoC from [download-artifact](https://github.com/actions/download-artifact)
=> 🧹 Update documentation

__mocks__/@actions/github.ts, __tests__/fixtures/only_pdfs.yml, __tests__/labeler.test.ts, __tests__/main.test.ts, tsconfig.json
This adds some basic tests to confirm the behavior of running the whole action. I'm using Jest mocks for the Github API.
My Jest knowledge is pretty minimal. In particular the way I'm mocking the GitHub API feels janky. Feedback appreciated!
=> 🧹 Add tests that run the whole action

README.md
The final example in the README.md has not had a language defined, so does not have syntax highlighting. This PR resolves that by setting it to `YML`, the same as the other code blocks.
=> Fix Code Block Type in Readme

__mocks__/@actions/github.ts, __tests__/labeler.test.ts, __tests__/main.test.ts, package.json
The lack of quotes around our recursive glob pattern was causing us to miss nested directories. No longer!
```
❍ npm run format
> labeler@3.0.0 format
> prettier --write **/*.ts
__tests__/labeler.test.ts 158ms
__tests__/main.test.ts 41ms
src/labeler.ts 70ms
src/main.ts 11ms
```
```
❍ npm run format
> labeler@3.0.0 format
> prettier --write "**/*.ts"
__mocks__/@actions/github.ts 155ms
__tests__/labeler.test.ts 14ms
__tests__/main.test.ts 38ms
src/labeler.ts 68ms
src/main.ts 9ms
```
=> Fix recursive globbing in our npm `format` script command and run all ts files through prettier 💅

README.md
- specified 'yml' syntax highlighting for a code block example in readme
=> docs(readme): specified 'yml' syntax highlighting

.github/workflows/build_test.yml, action.yml
Node 12 has an end of life on April 30, 2022.
This PR updates the default runtime to [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/), rather then node12. 
This is supported on all Actions Runners v2.285.0 or later.
=> Update default runtime to node16

README.md
As a means to reduce the privileges provided to the job executing, we
can document what the minimal `permissions` required for the Actions'
`GITHUB_TOKEN` is.
=> Clarify `permissions` required to use Action

__tests__/main.test.ts, dist/index.js, src/labeler.ts
Correctly check the truth value of the `sync-labels` input. Currently, `core.getInput` always returns a string, and `!!'false'` is `true`.
This pull request is a copy of [this one](https://github.com/actions/labeler/pull/480).
=> fix: correct reading of sync-labels input

README.md
The action will return
Error: HttpError: Resource not accessible by integration
when triggered on a PR on a forked repository.
=> Warn about the limitations of GitHub tokens

dist/index.js, package.json, src/labeler.ts
Labeler has a bunch of more or less related problems.
* it doesn't properly annotate its `action.yml`
* it confuses booleans and strings #404 
* it doesn't handle permissions errors #136
* it's actively hostile to forks (#136)
The general implementation to address this fits the outlines in https://github.com/actions/labeler/issues/136#issuecomment-1169411989
https://github.com/check-spelling/use-labeler/actions/runs/2729552526
Annotations
1 error and 1 warning
❌ [label](https://github.com/check-spelling/use-labeler/runs/7492592323?check_suite_focus=true#step:2:9)
Resource not accessible by integration
⚠️ [jsoref/labeler running under 'pull_request' is misconfigured](https://github.com/check-spelling/use-labeler/runs/7492592323?check_suite_focus=true#step:2:8)
It needs `permissions: …
=> Explain misconfigured workflow

.licenses/npm/minimatch.dep.yml, dist/index.js, package-lock.json, package.json
In the scope of this PR is updating the Minimatch dependency from `7.4.3` to the latest `9.0.3`. Although there is already a PR for this (https://github.com/actions/labeler/pull/608), there were some issues in the `check-dist` workflow, so I created this one to attempt to fix it.
Unit tests were ran and no errors were found.
=> Update Minimatch to 9.0.3, rebuild and fix licensing

dist/index.js, src/labeler.ts
Fix double negation typo on the file not found error message:
```diff
-The configuration file (path: /) isn't not found locally, fetching via the api
+The configuration file (path: /) was not found locally, fetching via the api
```
Note: I also changed the positive message for consistency, but I can revert if needed.
```diff
-The configuration file (path: /) is found locally, reading from the file
+The configuration file (path: /) was found locally, reading from the file
```
No documentation changes are required.
No tests were modified.
**Related issue:**
None
=> Fix double negation message typo

__tests__/changedFiles.test.ts, __tests__/fixtures/all_options.yml, __tests__/fixtures/any_and_all.yml, __tests__/fixtures/only_pdfs.yml, __tests__/labeler.test.ts, dist/index.js, src/changedFiles.ts, src/labeler.ts
In scope of this pull request, the structure of the configuration file (`.github/labeler.yml`) was changed from
```yml
LabelName:
- any:
- changed-files: ['list', 'of', 'globs']
- base-branch: ['list', 'of', 'regexps']
- head-branch: ['list', 'of', 'regexps']
- all:
- changed-files: ['list', 'of', 'globs']
- base-branch: ['list', 'of', 'regexps']
- head-branch: ['list', 'of', 'regexps']
```
to
```yml
LabelName:
- any:
- changed-files: 
- AnyGlobToAnyFile: ['list', 'of', 'globs']
- AnyGlobToAllFiles: ['list', 'of', 'globs']
- AllGlobsToAnyFile: ['list', 'of', 'globs']
- AllGlobsToAllFiles: ['list', 'of', 'globs']
- base-branch: ['list', 'of', 'regexps']
- head-branch: ['list', 'of', 'regexps']
- all:
- changed-files:
- AnyGlobToAnyFile: ['list', 'of', 'globs']
- …
```
=> [Beta] Implement the new structure of the match object for the changed-files section 

README.md, __tests__/changedFiles.test.ts, __tests__/fixtures/all_options.yml, __tests__/fixtures/any_and_all.yml, __tests__/fixtures/only_pdfs.yml, __tests__/labeler.test.ts, action.yml, dist/index.js, src/changedFiles.ts, src/utils.ts, src/utils/index.ts, src/utils/print-pattern.ts
In scope of this pull request, we implemented the suggestions collected in the [related announcement](https://github.com/actions/labeler/issues/575) and updated the documentation.
=> Apply suggestions for the beta version and update the documentation

README.md
I think this is a big gotcha that should be called out in the documentation. I've been trying to debug why the workflow did not run in https://github.com/go-gitea/gitea/pull/26962 for a long time, until I finally understood the underlying issue.
=> Add note regarding `pull_request_target` to README.md

README.md
In the scope of this PR, the `Readme.md` file was updated with additional examples and important note about `pull_request_target` event.
The embedded GitHub markdown syntax was used to highlight the note. After merging the PR the note should look like this:
**Related issue:**
https://github.com/actions/labeler/issues/712
=> Update readme with additional examples and important note about `pull_request_target` event

.github/workflows/basic-validation.yml, .github/workflows/check-dist.yml, .github/workflows/publish-immutable-actions.yml, README.md, action.yml, package-lock.json, package.json
Bump the required Node.js version to 24 in action.yml and package.json. Update @types/node to ^24.1.0 to match the new Node.js version.
Describe your changes.
**Related issue:**
Add link to the related issue.
=> Update Node.js version to 24 in action and dependencies

README.md, __tests__/labeler.test.ts, dist/index.js, src/labeler.ts
This pull request updates the GitHub Labeler Action documentation and error handling to clarify required permissions and provide better guidance for resolving issues. The changes include detailed permission requirements, alternative solutions for label creation, and improved error messaging in the code.
**Documentation Updates:**
* [`README.md`](diffhunk://#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5L261-R290): Expanded the explanation of required permissions for adding and creating labels (`pull-requests: write` and `issues: write`), added an example workflow configuration, and provided an alternative for manual label creation to avoid granting `issues: write` permission.
**Error Handling Improvements:**
* …
=> Improve Labeler Action Documentation and Error Handling for Permissions
